stages:
  data_ingestion:
    cmd: python src/cnnImageClassification/pipeline/stage01_data_ingestion.py
    deps:
      - src/cnnImageClassification/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/GestureDataset

  prepare_base_model:
    cmd: python src/cnnImageClassification/pipeline/stage02_prep_base_model.py
    deps:
        - src/cnnImageClassification/pipeline/stage02_prep_base_model.py
        - config/config.yaml
    params:
        - IMAGE_SIZE
        - BATCH_SIZE
        - EPOCHS
        - CLASSES
        - LOSS
        - METRICS
    outs:
        - artifacts/prepare_base_model



  training:
    cmd: python src/cnnImageClassification/pipeline/stage03_training.py
    deps:
      - src/cnnImageClassification/pipeline/stage03_training.py
      - src/cnnImageClassification/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/GestureDataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/cnnImageClassification/pipeline/stage04_evaluation.py
    deps:
      - src/cnnImageClassification/pipeline/stage04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/GestureDataset
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false